require("user.plugins-setup")
require("user.core.options")
require("user.core.keymaps")
require("user.plugins.comment")
require("user.plugins.ntree")
require("user.plugins.lualine")
require("user.plugins.nvim-cmp")
require("user.plugins.lsp.mason")
require("user.plugins.lsp.lspsaga")
require("user.plugins.lsp.lspconfig")
require("user.plugins.lsp.null_ls")
require("user.plugins.autopairs")
require("user.plugins.treesitter")
require("user.plugins.gitsigns")
require("user.plugins.winbar")

-- themes
require("user.themes.tokyonight")
